config/routes.rb
Rails.application.routes.draw do
  devise_for :headceos
  resources :questions
  devise_for :users
  get 'home/index'
get '/solve'=>'home#solve'
post '/evaluate'=>'home#evaluate'

  root 'home#index'

end

app/models/headceo.rb
class Headceo < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable,:recoverable, :rememberable, :trackable, :validatable
end

app/models/leaderboard.rb
class Leaderboard < ActiveRecord::Base
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
  def solve
  		@langs = HTTParty.get('http://api.hackerrank.com/checker/languages.json')
  		@names = @langs["languages"]["names"]
  		@codes = @langs["languages"]["codes"]
      # @ques=Question.find(params[:questions_id])
      @ques=Question.all

      # @testcases=@ques.testcases

  	end

  	def evaluate

  		permitted = params.permit("source","lang","testcases","api_key","format")
  		response = HTTParty.post("http://api.hackerrank.com/checker/submission.json",:body => permitted);
      
    end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :constraints, :testcases, :marks, :difficulty)
    end
end

app/controllers/solve_controller.rb
class SolveController < ApplicationController
  def solve
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
  <%= link_to "logOut", destroy_user_session_path ,method: :delete%>
<%= link_to " new_question", new_question_path,method: :get%>

app/views/home/solve.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%= form_tag '/evaluate',remote: true do %>

	<%= text_area_tag 'source'%>
	<%= hidden_field_tag 'testcases',(@ques.first.testcases)%>
	<%= select_tag 'lang', options_for_select(@names.collect{ |key,value| [value, @codes[key]] }) %>
	<%= select_tag 'format', options_for_select(["JSON","XML"]) %>
	<%= hidden_field_tag 'api_key','hackerrank|2357374-1588|c8cb820f84f230248f9117b777b64f017d2cad2f' %>
	<%= submit_tag 'Submit' %>

<% end %>
    <div class="ace-editor">
  <!-- <textarea></textarea> -->
</div>
<style media="screen">
.ace{
/*position: absolute;*/
color:white;
float:right;
background-color: black;
height: 400px;
width: 500px;
top: 0;
bottom: 0;
left: 0;
right: 0;
}

</style>
<script type="text/javascript">
$(document).ready(function() {
// initialize all Ace editors on the page.
$(".ace-editor").each(function(index, item) {
  initAceEditor(item);
});
});

function initAceEditor(container) {
container = $(container);
var textarea = container.find("textarea");
var aceEditorDiv = $('<div>', {
    "class": "ace"
}).insertBefore(textarea);

var aceEditor = ace.edit(aceEditorDiv[0]);
textarea.closest('form').submit(function() {
  textarea.val(aceEditor.getValue());
});
}

</script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineJudge</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :constraints %><br>
    <%= f.text_field :constraints %>
  </div>
  <div class="field">
    <%= f.label :testcases %><br>
    <%= f.text_field :testcases %>
  </div>
  <div class="field">
    <%= f.label :marks %><br>
    <%= f.number_field :marks %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.text_field :difficulty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Constraints</th>
      <th>Testcases</th>
      <th>Marks</th>
      <th>Difficulty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= question.constraints %></td>
        <td><%= question.testcases %></td>
        <td><%= question.marks %></td>
        <td><%= question.difficulty %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Solve', solve_path, method: :get %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Constraints:</strong>
  <%= @question.constraints %>
</p>

<p>
  <strong>Testcases:</strong>
  <%= @question.testcases %>
</p>

<p>
  <strong>Marks:</strong>
  <%= @question.marks %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @question.difficulty %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>